---
- name: Install Dependencies for Redhat/CentOS
  yum: name={{ item }} state=installed
  with_items:
    - sqlite-devel
    - gcc
    - gcc-c++
    - make
  when: ansible_os_family == "RedHat"

- name: Install Activesupport
  gem: name=activesupport version=4.2.5 state=present user_install={{ limit_to_user }} executable={{ gem_to_use }}

- name: Install Mailcatcher version {{ mailcatcher_version }}
  gem: name=mailcatcher version={{ mailcatcher_version }} state=present user_install={{ limit_to_user }} executable={{ gem_to_use }}
  when: "mailcatcher_version != 'latest'"

- name: Install Mailcatcher latest version
  gem: name=mailcatcher state={{ mailcatcher_version }} user_install={{ limit_to_user }} executable={{ gem_to_use }}
  when: "mailcatcher_version == 'latest'"
